// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPatternCTM(arg1, arg2) {
  return window['go']['internal']['App']['ExportPatternCTM'](arg1, arg2);
}

export function ExportRandomTexture(arg1, arg2) {
  return window['go']['internal']['App']['ExportRandomTexture'](arg1, arg2);
}

export function OpenTextureFile(arg1) {
  return window['go']['internal']['App']['OpenTextureFile'](arg1);
}

export function OpenTextureFiles(arg1) {
  return window['go']['internal']['App']['OpenTextureFiles'](arg1);
}
