// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function ExportPatternCTM(arg1:string,arg2:number):Promise<void>;

export function OpenTextureFile():Promise<internal.OpenTextureFileResp>;
