// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPatternCTM(arg1, arg2) {
  return window['go']['internal']['App']['ExportPatternCTM'](arg1, arg2);
}

export function OpenTextureFile() {
  return window['go']['internal']['App']['OpenTextureFile']();
}
